[package]
name = "rust-moodle-checker"
version = "0.1.0"
edition = "2021"

[dependencies]
ctrlc = "3.4.5"
html2text = "0.13.6"
moodle = "0.1.0"
serde_json = "1.0.135"
tokio = "1.43.0"
winapi = { version = "0.3.9", features = ["wincon"] }
